apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-2-service
  labels:
    app: devops-assignment-2-app
spec:
  type: LoadBalancer
  selector:
    app: devops-assignment-2-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
